In [4]:
import warnings
warnings.simplefilter(action = 'ignore' , category=FutureWarning)

In [5]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [6]:
from sklearn import preprocessing
from tensorflow.keras.utils import to_categorical

Y =  ['unacc','acc', 'acc','vgood', 'unacc', 'vgood','unacc','acc','good','vgood']
encoder = preprocessing.LabelEncoder()
encoder.fit(Y)

encoded_Y = encoder.transform(Y)
dummy_y = to_categorical(encoded_Y)
print(dummy_y)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
